export type UsStateCities = {
  state: string;
  abbrev: string;
  cities: string[];
};

/** All 50 states + DC, with major cities under each. */
export const US_STATE_CITIES: UsStateCities[] = [
  { state: "Alabama", abbrev: "AL", cities: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"] },
  { state: "Alaska", abbrev: "AK", cities: ["Anchorage", "Fairbanks", "Juneau"] },
  { state: "Arizona", abbrev: "AZ", cities: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Gilbert"] },
  { state: "Arkansas", abbrev: "AR", cities: ["Little Rock", "Fayetteville", "Fort Smith", "Springdale", "Jonesboro"] },
  {
    state: "California",
    abbrev: "CA",
    cities: [
      "Los Angeles",
      "San Diego",
      "San Jose",
      "San Francisco",
      "Sacramento",
      "Fresno",
      "Oakland",
      "Bakersfield",
      "Long Beach",
      "Anaheim",
    ],
  },
  { state: "Colorado", abbrev: "CO", cities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"] },
  { state: "Connecticut", abbrev: "CT", cities: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"] },
  { state: "Delaware", abbrev: "DE", cities: ["Wilmington", "Dover", "Newark"] },
  { state: "District of Columbia", abbrev: "DC", cities: ["Washington"] },
  {
    state: "Florida",
    abbrev: "FL",
    cities: [
      "Jacksonville",
      "Miami",
      "Tampa",
      "Orlando",
      "St. Petersburg",
      "Fort Lauderdale",
      "Tallahassee",
      "Cape Coral",
    ],
  },
  { state: "Georgia", abbrev: "GA", cities: ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens"] },
  { state: "Hawaii", abbrev: "HI", cities: ["Honolulu", "Hilo", "Kailua", "Kahului"] },
  { state: "Idaho", abbrev: "ID", cities: ["Boise", "Meridian", "Nampa", "Idaho Falls"] },
  {
    state: "Illinois",
    abbrev: "IL",
    cities: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Springfield"],
  },
  { state: "Indiana", abbrev: "IN", cities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"] },
  { state: "Iowa", abbrev: "IA", cities: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City"] },
  { state: "Kansas", abbrev: "KS", cities: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"] },
  { state: "Kentucky", abbrev: "KY", cities: ["Louisville", "Lexington", "Bowling Green"] },
  { state: "Louisiana", abbrev: "LA", cities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"] },
  { state: "Maine", abbrev: "ME", cities: ["Portland", "Lewiston", "Bangor"] },
  { state: "Maryland", abbrev: "MD", cities: ["Baltimore", "Columbia", "Germantown", "Silver Spring", "Annapolis"] },
  { state: "Massachusetts", abbrev: "MA", cities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"] },
  { state: "Michigan", abbrev: "MI", cities: ["Detroit", "Grand Rapids", "Warren", "Ann Arbor", "Lansing"] },
  { state: "Minnesota", abbrev: "MN", cities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"] },
  { state: "Mississippi", abbrev: "MS", cities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg"] },
  { state: "Missouri", abbrev: "MO", cities: ["Kansas City", "St. Louis", "Springfield", "Columbia"] },
  { state: "Montana", abbrev: "MT", cities: ["Billings", "Missoula", "Great Falls", "Bozeman"] },
  { state: "Nebraska", abbrev: "NE", cities: ["Omaha", "Lincoln", "Bellevue"] },
  { state: "Nevada", abbrev: "NV", cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas"] },
  { state: "New Hampshire", abbrev: "NH", cities: ["Manchester", "Nashua", "Concord"] },
  { state: "New Jersey", abbrev: "NJ", cities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton"] },
  { state: "New Mexico", abbrev: "NM", cities: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe"] },
  {
    state: "New York",
    abbrev: "NY",
    cities: ["New York", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"],
  },
  {
    state: "North Carolina",
    abbrev: "NC",
    cities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"],
  },
  { state: "North Dakota", abbrev: "ND", cities: ["Fargo", "Bismarck", "Grand Forks"] },
  { state: "Ohio", abbrev: "OH", cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"] },
  { state: "Oklahoma", abbrev: "OK", cities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"] },
  { state: "Oregon", abbrev: "OR", cities: ["Portland", "Salem", "Eugene", "Gresham", "Bend"] },
  {
    state: "Pennsylvania",
    abbrev: "PA",
    cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Harrisburg"],
  },
  { state: "Rhode Island", abbrev: "RI", cities: ["Providence", "Cranston", "Warwick"] },
  { state: "South Carolina", abbrev: "SC", cities: ["Charleston", "Columbia", "North Charleston", "Greenville"] },
  { state: "South Dakota", abbrev: "SD", cities: ["Sioux Falls", "Rapid City", "Aberdeen"] },
  { state: "Tennessee", abbrev: "TN", cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga"] },
  {
    state: "Texas",
    abbrev: "TX",
    cities: [
      "Houston",
      "San Antonio",
      "Dallas",
      "Austin",
      "Fort Worth",
      "El Paso",
      "Arlington",
      "Corpus Christi",
    ],
  },
  { state: "Utah", abbrev: "UT", cities: ["Salt Lake City", "West Valley City", "Provo", "West Jordan"] },
  { state: "Vermont", abbrev: "VT", cities: ["Burlington", "South Burlington", "Rutland"] },
  {
    state: "Virginia",
    abbrev: "VA",
    cities: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Arlington", "Alexandria"],
  },
  { state: "Washington", abbrev: "WA", cities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"] },
  { state: "West Virginia", abbrev: "WV", cities: ["Charleston", "Huntington", "Morgantown"] },
  { state: "Wisconsin", abbrev: "WI", cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha"] },
  { state: "Wyoming", abbrev: "WY", cities: ["Cheyenne", "Casper", "Laramie"] },
];
